#!/bin/sh
[Unit]
Description=Tests systemd to daemonize a Go binary
Wants=network.target
After=network.target

[Service]
Type=simple
User=root
DynamicUser=yes
ExecStart=/home/pi/go/start-robot-arm.sh
Restart=always
RestartSec=3

[Install]
WantedBy=multi-user.target